// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLuqxNGSJuJPzvS4nIK8fd_TSRytIjKM',
    appId: '1:1084029523403:web:17df2742d6846b0550524e',
    messagingSenderId: '1084029523403',
    projectId: 'pywara-99e8f',
    authDomain: 'pywara-99e8f.firebaseapp.com',
    storageBucket: 'pywara-99e8f.firebasestorage.app',
    measurementId: 'G-MY7949H7TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3bx4-O-yx3x0RYoRQD96DPK0WcCXTtps',
    appId: '1:1084029523403:android:7b696bb91bffec1750524e',
    messagingSenderId: '1084029523403',
    projectId: 'pywara-99e8f',
    storageBucket: 'pywara-99e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oMBQgvb1C3SQoRpjmE1T4-YP-sdvaAg',
    appId: '1:1084029523403:ios:40f7e2d5c1663e2950524e',
    messagingSenderId: '1084029523403',
    projectId: 'pywara-99e8f',
    storageBucket: 'pywara-99e8f.firebasestorage.app',
    iosBundleId: 'com.example.pywara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7oMBQgvb1C3SQoRpjmE1T4-YP-sdvaAg',
    appId: '1:1084029523403:ios:40f7e2d5c1663e2950524e',
    messagingSenderId: '1084029523403',
    projectId: 'pywara-99e8f',
    storageBucket: 'pywara-99e8f.firebasestorage.app',
    iosBundleId: 'com.example.pywara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLuqxNGSJuJPzvS4nIK8fd_TSRytIjKM',
    appId: '1:1084029523403:web:fc982aab4e6d717d50524e',
    messagingSenderId: '1084029523403',
    projectId: 'pywara-99e8f',
    authDomain: 'pywara-99e8f.firebaseapp.com',
    storageBucket: 'pywara-99e8f.firebasestorage.app',
    measurementId: 'G-TE4R5TSMME',
  );
}
